### ISSUE TITLE
Font size doesn't work

### ISSUE THREAD

**Issue by linakima** [OlegZuev/Guide-XUnity.AutoTranslator-and-BepInEx-for-il2cpp-games#1]
Hi there! 
I have installed the fonts but all the text is very small.
What should I change?
It is just the BepInEx module without the Sugoi module.
I have taken the fonts from the [following thread](https://github.com/bbepis/XUnity.AutoTranslator/releases/tag/v5.2.0) (tmp_font_assetbundles.zip)

![1](https://github.com/OlegZuev/Guide-XUnity.AutoTranslator-and-BepInEx-for-il2cpp-games/assets/34077156/9266cf48-7000-411e-bfff-22ea10d69398)
![2](https://github.com/OlegZuev/Guide-XUnity.AutoTranslator-and-BepInEx-for-il2cpp-games/assets/34077156/b85553d1-9d9d-4411-a67d-b4f69d879101)

**Comment by OlegZuev** [comment]
Sadly, cant help with that. My only goal was to make XUnity.AutoTranslator work with il2cpp Unity games for basic translation. Because many games use il2cpp nowadays I decided to make a guide how to make it work and share with others.
