### ISSUE TITLE
why almost all dlls oif this archive have a trojan alert?

### ISSUE THREAD

**Issue by KuKuKuK** [OlegZuev/Guide-XUnity.AutoTranslator-and-BepInEx-for-il2cpp-games#2]
can you explain it? or you are just evil?

**Comment by OlegZuev** [comment]
Because they dont. I'm using it myself and have no issues. Of course if you're too paranoid you can just opt to not use it at all 🤷‍♂️

**Comment by KuKuKuK** [comment]
This is paranoid? i'm using it too and i don't care if it have or not i don't have anything worth.
but i shared it with some people and that's why i asked this.
![gope](https://github.com/OlegZuev/Guide-XUnity.AutoTranslator-and-BepInEx-for-il2cpp-games/assets/10531074/c42d6725-e937-4819-8727-0508ca8af084)

**Comment by OlegZuev** [comment]
Well, all questions to BepInEx devs then. Only XUnity.AutoTranslator was changed to make it work with lastest version of BepInEx

**Comment by OlegZuev** [comment]
But, to my opinion, it's just false alarm due to how BepInEx works

**Comment by KuKuKuK** [comment]
i think its a false positive too but you know its scary asf, not for me but for these ppl who have their info on the computer.
well
